### ISSUE TITLE
Small improvement on blockquote styling

### ISSUE THREAD

**Issue by femto-code** [redsolver/noteless#44]
There's currently no styling to blockquotes, which makes it hard to tell if it's a paragraph or a quote.
Let's try this CSS for blockquote styling:
```CSS
blockquote{
  padding: .75em .5em .75em 1em;
  background: white;
  border-left: 0.5em solid #DDD;
}

blockquote::before {
  display: block;
  height: 0;
  content: "“";
  margin-left: -.95em;
  font: italic 400%/1 Open Serif,Georgia,"Times New Roman", serif;
  color: #999;
}

/* for nested paragraphs in block quotes */
blockquote p {
  display: inline;
}
```
Taken from here ([https://github.com/nteract/nteract/issues/810](https://github.com/nteract/nteract/issues/810)) with preview images! Would this be possible in Noteless app environment?
